apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels: 
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.container.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "backend.fullname" . }}
          image: {{ .Values.backend.container.image }}
          volumeMounts:
            - name: firebase-config
              mountPath: /etc/firebase.json
              subPath: firebase.json
              readOnly: true
            - name: cloudinary-config
              mountPath: /etc/cloudinary.json
              subPath: cloudinary.json
              readOnly: true
          imagePullPolicy: "Always"
          ports:
            - name: http
              containerPort: {{ .Values.backend.container.port }}
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: POSTGRES_PORT
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: firebase-config
          secret:
            secretName: {{ .Values.firebase.secretName }}
            items:
              - key: {{ .Values.firebase.secretKey }}
                path: firebase.json
        - name: cloudinary-config
          secret:
            secretName: {{ .Values.cloudinary.secretName }}
            items:
              - key: {{ .Values.cloudinary.secretKey }}
                path: cloudinary.json

