#version: '3.5'

services:
  db:
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
      - "./pg-init.sql:/docker-entrypoint-initdb.d/master_db_init.sql"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
volumes:
  pgdata: