spring:
  config:
    activate:
      on-profile: local

firebase:
  credentials: classpath:firebase/firebase.json

cloudinary:
  credentials: classpath:cloudinary/cloudinary.json

app:
  frontend:
    origin: "http://localhost:5173"