spring:
  datasource:
    url: jdbc:postgresql://localhost:5455/postgres
    username: db_user
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migrations