spring:
  config:
    import:
      - "application-local.yml"

  datasource:
   url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5455}/${POSTGRES_DB:postgres}
   username: ${POSTGRES_USER:db_user}
   password: ${POSTGRES_PASSWORD:password}
   driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migrations

  jpa:
    enabled: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
app:
  frontend:
    origin: "https://aurora-chat.devbstaging.com"

firebase:
  credentials: /etc/firebase.json

cloudinary:
  credentials: /etc/cloudinary.json


